name: Build and push CIRCT CI build image

on:
  workflow_dispatch:

jobs:
  build-mase-build-image:
    name: Build and push Docker CI builds
    runs-on: ubuntu-latest
    steps:
      - name: Get MASE images repo
        uses: actions/checkout@v2
      - name: Build and push image
        working-directory: ./circt-ci-build
        run: |
          TAG=$(date -u +%Y%m%d%H%M%S)
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build . --build-arg UID=1001 --build-arg GID=1000 --build-arg VHLS_PATH=. -f Docker/Dockerfile --tag ghcr.io/${{github.repository}}/circt-ci-build:$TAG Docker
          docker push ghcr.io/${{github.repository}}/circt-ci-build:$TAG
          docker tag ghcr.io/${{github.repository}}/circt-ci-build:$TAG ghcr.io/${{github.repository}}/circt-ci-build:latest
          docker push ghcr.io/${{github.repository}}/circt-ci-build:latest
